accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
    mnemonic: "cinnamon legend sword giant master simple visit action level ancient day rubber pigeon filter garment hockey stay water crawl omit airport venture toilet oppose"
  - name: bob
    coins: ["10000token", "100000000stake"]
    mnemonic: "stamp later develop betray boss ranch abstract puzzle calm right bounce march orchard edge correct canal fault miracle void dutch lottery lucky observe armed"
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
genesis:
  chain_id: "chihuahuaa"