swagger: '2.0'
info:
  title: Chihuahua - gRPC Gateway docs
  description: A REST interface for state queries
  version: 1.0.0
paths:
  /chihuahua/feeburn/params:
    get:
      summary: Parameters queries the parameters of the module.
      operationId: AuthParams
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                description: params holds all the parameters of this module.
                type: object
                properties:
                  txFeeBurnPercent:
                    type: string
            description: >-
              QueryParamsResponse is response type for the Query/Params RPC
              method.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      tags:
        - Query
definitions:
  chihuahua.feeburn.Params:
    type: object
    properties:
      txFeeBurnPercent:
        type: string
    description: Params defines the parameters for the module.
  chihuahua.feeburn.QueryParamsResponse:
    type: object
    properties:
      params:
        description: params holds all the parameters of this module.
        type: object
        properties:
          txFeeBurnPercent:
            type: string
    description: QueryParamsResponse is response type for the Query/Params RPC method.
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
