run:
  tests: false
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  disable-all: true
  enable:
    - depguard
    - dogsled
    - exportloopref
    - goconst
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - revive
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused

issues:
  exclude-rules:
    - text: "Use of weak random number generator"
      linters:
        - gosec

linters-settings:
  nolintlint:
    allow-leading-space: true
