# start with docker-compose -f tokentransfer.yml up -d

version: '3'

services:

  chihuahuaa:
    container_name: chihuahuaa
    image: "chihuahuaa"
    ports:
      - "26657:26657"
      - "1317:1317"
      - "4500:4500"
    networks:
      - tokendemo

  chihuahuab:
    container_name: chihuahuab
    image: "chihuahuab"
    ports:
      - "26658:26657"
      - "1318:26657"
      - "4501:26657"
    networks:
      - tokendemo

  relayer_hermes:
    profiles: ["hermes"]
    build: ./relayer_hermes
    container_name: relayer
    image: "relayer_hermes"
    tty: true
    stdin_open: true
    networks:
      - tokendemo

  relayer_go:
    profiles: ["go"]
    build: ./relayer_go
    container_name: relayer
    image: "relayer_go"
    tty: true
    stdin_open: true
    networks:
      - tokendemo

networks:
    tokendemo: