// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/tokenfactory/v1beta1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// WeightedAddress represents an address with a weight assigned to it.
// The weight is used to determine the proportion of the total minted
// tokens to be minted to the address.
type WeightedAddress struct {
	Address string                      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
	Weight  cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=weight,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"weight" yaml:"weight"`
}

func (m *WeightedAddress) Reset()         { *m = WeightedAddress{} }
func (m *WeightedAddress) String() string { return proto.CompactTextString(m) }
func (*WeightedAddress) ProtoMessage()    {}
func (*WeightedAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8299d306f3ff47, []int{0}
}
func (m *WeightedAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WeightedAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WeightedAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WeightedAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedAddress.Merge(m, src)
}
func (m *WeightedAddress) XXX_Size() int {
	return m.Size()
}
func (m *WeightedAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedAddress.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedAddress proto.InternalMessageInfo

func (m *WeightedAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// Params defines the parameters for the tokenfactory module.
type Params struct {
	DenomCreationFee github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=denom_creation_fee,json=denomCreationFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"denom_creation_fee" yaml:"denom_creation_fee"`
	// if denom_creation_fee is an empty array, then this field is used to add more gas consumption
	// to the base cost.
	// https://github.com/CosmWasm/token-factory/issues/11
	DenomCreationGasConsume    uint64                                 `protobuf:"varint,2,opt,name=denom_creation_gas_consume,json=denomCreationGasConsume,proto3" json:"denom_creation_gas_consume,omitempty" yaml:"denom_creation_gas_consume"`
	BuildersCommission         github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=builders_commission,json=buildersCommission,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"builders_commission" yaml:"builders_commission"`
	BuildersAddresses          []WeightedAddress                      `protobuf:"bytes,4,rep,name=builders_addresses,json=buildersAddresses,proto3" json:"builders_addresses" yaml:"builders_addresses"`
	FreeMintWhitelistAddresses []string                               `protobuf:"bytes,5,rep,name=free_mint_whitelist_addresses,json=freeMintWhitelistAddresses,proto3" json:"free_mint_whitelist_addresses,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8299d306f3ff47, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDenomCreationFee() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.DenomCreationFee
	}
	return nil
}

func (m *Params) GetDenomCreationGasConsume() uint64 {
	if m != nil {
		return m.DenomCreationGasConsume
	}
	return 0
}

func (m *Params) GetBuildersAddresses() []WeightedAddress {
	if m != nil {
		return m.BuildersAddresses
	}
	return nil
}

func (m *Params) GetFreeMintWhitelistAddresses() []string {
	if m != nil {
		return m.FreeMintWhitelistAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*WeightedAddress)(nil), "osmosis.tokenfactory.v1beta1.WeightedAddress")
	proto.RegisterType((*Params)(nil), "osmosis.tokenfactory.v1beta1.Params")
}

func init() {
	proto.RegisterFile("osmosis/tokenfactory/v1beta1/params.proto", fileDescriptor_cc8299d306f3ff47)
}

var fileDescriptor_cc8299d306f3ff47 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x63, 0x1a, 0x82, 0x6a, 0xc4, 0xaf, 0x03, 0x89, 0x24, 0x80, 0x9d, 0x7a, 0x40, 0xa9,
	0x44, 0x6d, 0x15, 0x3a, 0xa0, 0x6e, 0x89, 0x11, 0x2c, 0x89, 0x84, 0xbc, 0x54, 0x62, 0xb1, 0x2e,
	0xf6, 0x8b, 0x7d, 0x4a, 0xec, 0x8b, 0x7c, 0x67, 0x4a, 0x06, 0xc4, 0xbf, 0x80, 0x84, 0xc4, 0xcc,
	0xcc, 0x5f, 0x92, 0x81, 0xa1, 0x23, 0x62, 0x30, 0x28, 0x59, 0x98, 0xf3, 0x17, 0xa0, 0xdc, 0x9d,
	0xa3, 0xa4, 0xad, 0x2a, 0x26, 0xfb, 0xde, 0xfb, 0xbe, 0xcf, 0xbd, 0xf7, 0xbd, 0x3b, 0x7d, 0x9f,
	0xb2, 0x84, 0x32, 0xc2, 0x1c, 0x4e, 0x47, 0x90, 0x0e, 0x71, 0xc0, 0x69, 0x36, 0x75, 0xde, 0x1f,
	0x0e, 0x80, 0xe3, 0x43, 0x67, 0x82, 0x33, 0x9c, 0x30, 0x7b, 0x92, 0x51, 0x4e, 0xd1, 0x63, 0x25,
	0xb5, 0x37, 0xa5, 0xb6, 0x92, 0x36, 0x1f, 0x44, 0x34, 0xa2, 0x42, 0xe8, 0xac, 0xfe, 0x64, 0x4d,
	0xf3, 0xe8, 0x4a, 0x3c, 0xce, 0x79, 0x4c, 0x33, 0xc2, 0xa7, 0x7d, 0xe0, 0x38, 0xc4, 0x1c, 0xab,
	0xaa, 0x46, 0x20, 0xca, 0x7c, 0x89, 0x93, 0x0b, 0x95, 0x32, 0xe4, 0xca, 0x19, 0x60, 0x06, 0x6b,
	0x4e, 0x40, 0x49, 0x2a, 0xf3, 0xd6, 0x17, 0x4d, 0xbf, 0x73, 0x02, 0x24, 0x8a, 0x39, 0x84, 0x9d,
	0x30, 0xcc, 0x80, 0x31, 0xf4, 0x4c, 0xbf, 0x81, 0xe5, 0x6f, 0x5d, 0x6b, 0x69, 0xed, 0xdd, 0x2e,
	0x5a, 0x16, 0xe6, 0xed, 0x29, 0x4e, 0xc6, 0xc7, 0x96, 0x4a, 0x58, 0x5e, 0x29, 0x41, 0x3d, 0xbd,
	0x76, 0x2a, 0x00, 0xf5, 0x6b, 0x42, 0x7c, 0x34, 0x2b, 0xcc, 0xca, 0xaf, 0xc2, 0x7c, 0x24, 0x77,
	0x66, 0xe1, 0xc8, 0x26, 0xd4, 0x49, 0x30, 0x8f, 0xed, 0x1e, 0x44, 0x38, 0x98, 0xbe, 0x82, 0x60,
	0x59, 0x98, 0xb7, 0x24, 0x4f, 0x96, 0x5a, 0x9e, 0x62, 0x1c, 0x57, 0xff, 0x7e, 0x33, 0x35, 0xeb,
	0x47, 0x55, 0xaf, 0xbd, 0x15, 0x5e, 0xa2, 0xaf, 0x9a, 0x8e, 0x42, 0x48, 0x69, 0xe2, 0x07, 0x19,
	0x60, 0x4e, 0x68, 0xea, 0x0f, 0x01, 0xea, 0x5a, 0x6b, 0xa7, 0x7d, 0xf3, 0x79, 0xc3, 0x56, 0xc3,
	0xae, 0xc6, 0x2b, 0xad, 0xb5, 0x5d, 0x4a, 0xd2, 0x6e, 0x7f, 0xd5, 0xc6, 0xb2, 0x30, 0x1b, 0x72,
	0x9f, 0x8b, 0x08, 0xeb, 0xfb, 0x6f, 0xb3, 0x1d, 0x11, 0x1e, 0xe7, 0x03, 0x3b, 0xa0, 0x89, 0xb2,
	0x4d, 0x7d, 0x0e, 0x58, 0x38, 0x72, 0xf8, 0x74, 0x02, 0x4c, 0xd0, 0x98, 0x77, 0x57, 0x00, 0x5c,
	0x55, 0xff, 0x1a, 0x00, 0x0d, 0xf5, 0xe6, 0x39, 0x68, 0x84, 0x99, 0x1f, 0xd0, 0x94, 0xe5, 0x09,
	0x08, 0x2f, 0xaa, 0xdd, 0xfd, 0x59, 0x61, 0x6a, 0xcb, 0xc2, 0xdc, 0xbb, 0xb4, 0x89, 0x0d, 0xbd,
	0xe5, 0x3d, 0xdc, 0xda, 0xe0, 0x0d, 0x66, 0xae, 0xcc, 0xa0, 0x8f, 0xfa, 0xfd, 0x41, 0x4e, 0xc6,
	0x21, 0x64, 0x2b, 0x75, 0x92, 0x10, 0xc6, 0x08, 0x4d, 0xeb, 0x3b, 0xc2, 0xec, 0x9e, 0x32, 0xfb,
	0xe9, 0x7f, 0x0c, 0x22, 0x7d, 0x6f, 0xca, 0x56, 0x2e, 0x41, 0x5a, 0x1e, 0x2a, 0xa3, 0xee, 0x3a,
	0x88, 0x3e, 0xe9, 0xeb, 0xa8, 0xaf, 0x8e, 0x1c, 0x58, 0xbd, 0x2a, 0xec, 0x3f, 0xb0, 0xaf, 0xba,
	0xe2, 0xf6, 0xb9, 0x7b, 0xd5, 0xdd, 0xdb, 0x3e, 0x92, 0x8b, 0x58, 0xcb, 0xbb, 0x57, 0x06, 0x3b,
	0x65, 0x0c, 0x75, 0xf4, 0x27, 0xc3, 0x0c, 0xc0, 0x4f, 0x48, 0xca, 0xfd, 0xd3, 0x98, 0x70, 0x18,
	0x13, 0xc6, 0x37, 0x7a, 0xb9, 0xde, 0xda, 0x69, 0xef, 0x7a, 0xcd, 0x95, 0xa8, 0x4f, 0x52, 0x7e,
	0x52, 0x4a, 0xd6, 0x88, 0xae, 0x37, 0x9b, 0x1b, 0xda, 0xd9, 0xdc, 0xd0, 0xfe, 0xcc, 0x0d, 0xed,
	0xf3, 0xc2, 0xa8, 0x9c, 0x2d, 0x8c, 0xca, 0xcf, 0x85, 0x51, 0x79, 0xf7, 0x72, 0xc3, 0x37, 0x37,
	0x26, 0x71, 0x8e, 0xe3, 0x1c, 0xbb, 0x31, 0x26, 0xa9, 0x13, 0x94, 0x4b, 0xe7, 0xc3, 0xf6, 0x6b,
	0x14, 0x6e, 0x0e, 0x6a, 0xe2, 0xfd, 0xbc, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x47, 0x72,
	0x6a, 0x11, 0x04, 0x00, 0x00,
}

func (this *WeightedAddress) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WeightedAddress)
	if !ok {
		that2, ok := that.(WeightedAddress)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	if !this.Weight.Equal(that1.Weight) {
		return false
	}
	return true
}
func (m *WeightedAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WeightedAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WeightedAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Weight.Size()
		i -= size
		if _, err := m.Weight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FreeMintWhitelistAddresses) > 0 {
		for iNdEx := len(m.FreeMintWhitelistAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.FreeMintWhitelistAddresses[iNdEx])
			copy(dAtA[i:], m.FreeMintWhitelistAddresses[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.FreeMintWhitelistAddresses[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.BuildersAddresses) > 0 {
		for iNdEx := len(m.BuildersAddresses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BuildersAddresses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.BuildersCommission.Size()
		i -= size
		if _, err := m.BuildersCommission.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.DenomCreationGasConsume != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DenomCreationGasConsume))
		i--
		dAtA[i] = 0x10
	}
	if len(m.DenomCreationFee) > 0 {
		for iNdEx := len(m.DenomCreationFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DenomCreationFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *WeightedAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.Weight.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DenomCreationFee) > 0 {
		for _, e := range m.DenomCreationFee {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.DenomCreationGasConsume != 0 {
		n += 1 + sovParams(uint64(m.DenomCreationGasConsume))
	}
	l = m.BuildersCommission.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.BuildersAddresses) > 0 {
		for _, e := range m.BuildersAddresses {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.FreeMintWhitelistAddresses) > 0 {
		for _, s := range m.FreeMintWhitelistAddresses {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WeightedAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WeightedAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WeightedAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Weight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DenomCreationFee = append(m.DenomCreationFee, types.Coin{})
			if err := m.DenomCreationFee[len(m.DenomCreationFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomCreationGasConsume", wireType)
			}
			m.DenomCreationGasConsume = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DenomCreationGasConsume |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuildersCommission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BuildersCommission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuildersAddresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuildersAddresses = append(m.BuildersAddresses, WeightedAddress{})
			if err := m.BuildersAddresses[len(m.BuildersAddresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FreeMintWhitelistAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FreeMintWhitelistAddresses = append(m.FreeMintWhitelistAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
